// Generated by CoffeeScript 1.6.3
(function() {
  var code_eq, p, _ref;

  _ref = require('./helper'), p = _ref.p, code_eq = _ref.code_eq;

  describe('basic', function() {
    it('simple', function() {
      return code_eq("x!", "var _this = this; x(function(_$$_0) { return _$$_0; });");
    });
    it('with returns', function() {
      return code_eq("y = x!", "var y, _this = this; x(function() { return y = arguments[0]; });");
    });
    return it('full feature', function() {
      return code_eq("x, y = a! b, c", "var x, y, _this = this; a(b, c, function() { return x = arguments[0], y = arguments[1], x; });");
    });
  });

}).call(this);
